### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by abijr** [abijr/dotfiles#1]
## TODO
- [ ] Dockerfile to test installation
- [ ] Vimrc
- [ ] Atom configs
- [ ] Atom packages
- [ ] TODO greeting for terminal
- [ ] Git config (separate username and stuff from ~/.gitconfig?)
